import type { ReactNode } from "react";

/**
 * A chapter body Jacob hasn't written himself yet.
 *
 * The /bio chapters were first drafted by ChatGPT from his notes. A draft
 * sits inside <Draft>, which sets it in grey on a grey ground under a note
 * saying where it came from, so nobody reads it as his voice. Rewriting a
 * chapter means replacing the whole block with his own prose.
 *
 * The reader's paragraph component colours its text ink, so the grey is
 * forced onto the prose inside. The note is a div, not a p, to stay out of
 * that override.
 */
export function Draft({ children }: { children: ReactNode }) {
  return (
    <section
      aria-label="Draft generated by ChatGPT"
      className="my-8 rounded-md bg-[var(--color-bg-1)] px-5 py-5 sm:px-7 sm:py-6 [&_a]:!text-[var(--color-ink-dim)] [&_code]:!text-[var(--color-ink-dim)] [&_p]:!text-[var(--color-ink-dim)]"
    >
      <div className="mb-2 font-[family-name:var(--font-mono)] text-[0.68rem] tracking-[0.14em] text-[var(--color-ink-mute)] uppercase">
        Generated by ChatGPT. I still need to write this chapter in my own voice.
      </div>
      {children}
    </section>
  );
}
